name: Build doc
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Get Python running
        run: 'python -m pip install --user --upgrade --progress-bar off pip

          python -m pip install --user --upgrade --progress-bar off -r requirements_all.txt

          python -m pip install --user --upgrade --progress-bar off -r docs/requirements.txt

          python -m pip install --user --upgrade --progress-bar off ipython sphinx-gallery
          memory_profiler

          python -m pip install --user -e .

          '
      - id: measurement-4
        name: Record Measurement After Get Python running
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Get Python running
          task: get-measurement
      - name: Check installation
        run: 'which python

          python -c "import ot"

          '
      - id: measurement-6
        name: Record Measurement After Check installation
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Check installation
          task: get-measurement
      - name: Generate HTML docs
        uses: rickstaa/sphinx-action@master
        with:
          docs-folder: docs/
      - uses: actions/upload-artifact@v4
        with:
          name: Documentation
          path: docs/build/html/
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
