name: Build wheels
on:
  push:
    branches:
      - main

jobs:
  build_all_wheels:
    if: contains(github.event.head_commit.message, 'build all wheels')
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: 'python -m pip install --upgrade pip setuptools

          '
      - id: measurement-4
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - name: Install cibuildwheel
        run: 'python -m pip install cibuildwheel==3.1.4

          '
      - id: measurement-6
        name: Record Measurement After Install cibuildwheel
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install cibuildwheel
          task: get-measurement
      - if: runner.os == 'Linux'
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - env:
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_ARCHS_MACOS: x86_64 universal2 arm64
          CIBW_SKIP: pp*-win* pp*-macosx* cp2* pp* cp*musl* *i686
        name: Build wheels
        run: 'python -m cibuildwheel --output-dir wheelhouse

          '
      - id: measurement-9
        name: Record Measurement After Build wheels
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Build wheels
          task: get-measurement
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ strategy.job-index }}
          path: ./wheelhouse
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
  build_wheels:
    if: contains(github.event.head_commit.message, 'build wheels')
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: 'python -m pip install --upgrade pip setuptools

          '
      - id: measurement-4
        name: Record Measurement After Install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install dependencies
          task: get-measurement
      - name: Install cibuildwheel
        run: 'python -m pip install cibuildwheel==3.1.4

          '
      - id: measurement-6
        name: Record Measurement After Install cibuildwheel
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install cibuildwheel
          task: get-measurement
      - env:
          CIBW_SKIP: pp*-win* pp*-macosx* cp2* pp* cp36* cp37* cp38* cp*musl* *i686
        name: Build wheels
        run: 'python -m cibuildwheel --output-dir wheelhouse

          '
      - id: measurement-8
        name: Record Measurement After Build wheels
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Build wheels
          task: get-measurement
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ strategy.job-index }}
          path: ./wheelhouse
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
